version: "3.9"
services:
  app:
    build: .
    restart: always
    ports: 
      - "5011:8080"
    depends_on:
      - postgres

    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=swiftuidb;Username=user;Password=password
      - ASPNETCORE_URLS=http://+:8080




  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: swiftuidb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  pgdata:
